(*!- \coqadd{\*:}{ } *)
(*!- \coqadd{:\*}{ } *)
(*!- \coqadd{\*m:}{ } *)
(*!- \coqadd{\*ml:}{ } *)
(*!- \coqadd{\*m\b}{ } *)
(*!- \coqadd{\*ml\b}{ } *)
(*!- \coqadd{\*mr\b}{ } *)
(*!- \coqadd{\.\*}{\hadamard} *)
(*!- \coqadd{\bvec\b}{\vec} *)
(*!- \coqadd{\bsym\b}{\mathrm{sym}} *)
(*!- \coqadd{\\\\d}{\partial} *)
(*!- \coqadd{\*o\b}{\otimes} *)
(*!- \coqadd{\*ol\b}{\otimes} *)
(*!- \coqadd{\*or\b}{\otimes} *)
(*!- \coqadd{\^T\b}{\tr} *)
(*!- \coqadd{\^\+}{^\dagger} *)
(*!- \coqadd{\^\^\s*-1}{^{-1}} *)
(*!- \coqadd{\^-\s*(\w+)}{^{-\1}} *)
(*!- \coqadd{\\m\b}{\v m} *)
(*!- \coqadd{~WR\b}{\widetilde{WR}} *)
(*!- \coqadd{~W\b}{\tW} *)
(*!- \coqadd{~U\b}{\widetilde{U}} *)
(*!- \coqadd{\bV\*}{{V^*}} *)
(*!- \coqadd{~V\*}{{\widetilde{V}^*}} *)
(*!- \coqadd{\bv\*}{{v^*}} *)
(*!- \coqadd{\beps1\b}{\epsilon_1} *)
(*!- \coqadd{\bW\b}{\mW} *)
(*!- \coqadd{\bM\b}{\mM} *)
(*!- \coqadd{\bU\b}{\mU} *)
(*!- \coqadd{\bV\b}{V} *)
